//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LagerMan {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class ExcelSunpower : global::System.Configuration.ApplicationSettingsBase {
        
        private static ExcelSunpower defaultInstance = ((ExcelSunpower)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ExcelSunpower())));
        
        public static ExcelSunpower Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("17,1")]
        public string sp_dataStart {
            get {
                return ((string)(this["sp_dataStart"]));
            }
            set {
                this["sp_dataStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8,2")]
        public string sp_prodName {
            get {
                return ((string)(this["sp_prodName"]));
            }
            set {
                this["sp_prodName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("110102")]
        public int supplier_id {
            get {
                return ((int)(this["supplier_id"]));
            }
            set {
                this["supplier_id"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7,2")]
        public string sp_packeList {
            get {
                return ((string)(this["sp_packeList"]));
            }
            set {
                this["sp_packeList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6,8")]
        public string sp_quantity {
            get {
                return ((string)(this["sp_quantity"]));
            }
            set {
                this["sp_quantity"] = value;
            }
        }
    }
}
